### ISSUE TITLE
RatingControlSample docs link is broken

### ISSUE THREAD

**Issue by samtun** [AvaloniaUI/Avalonia.Samples#103]
## Describe the bug

The Controls link in the RatingControlSample is broken (404 - https://docs.avaloniaui.net/docs/basics/user-interface/controls/creating-controls/choosing-a-custom-contro-type).

- [X] Outdated links

## Sample affected
[RatingControlSample](https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CustomControls/RatingControlSample)

## Proposed solution
* Update the link to whatever page fit's here (this one maybe? https://docs.avaloniaui.net/docs/basics/user-interface/controls/).
  * Or replace the link with anything fitting if the old information is not available anymore

## Screenshots
![Screenshot 2024-10-09 at 15 38 35](https://github.com/user-attachments/assets/093c6b29-93ac-4352-8241-5bc26f623938)

**Comment by timunie** [comment]
thx for finding this. Was actually a missing char 🙈
