### ISSUE TITLE
Vlsual Designer fails on .NET 9

### ISSUE THREAD

**Issue by francotiveron** [AvaloniaUI/Avalonia.Samples#108]
One or more errors occurred. (Internal compiler error: Unable to resolve type Avalonia.Data.MultiBinding (XDataTypeTransformer) Line 1, position 2.) (Internal compiler error: Unable to resolve type Avalonia.Data.MultiBinding (AvaloniaXamlIlClassesTransformer) Line 1, position 2.) (Internal compiler error: Unable to resolve type Avalonia.Data.MultiBinding (AvaloniaXamlIlThemeVariantProviderTransformer) Line 1, position 2.) (Internal compiler error: Unable to resolve type Avalonia.Data.MultiBinding (AvaloniaXamlIlControlTemplatePriorityTransformer) Line 1, position 2.)

**Comment by timunie** [comment]
Hello @francotiveron 

We need much more information to help. First of all, there is no visual designer for Avalonia yet, only a previewer. And if you mean the previewer, please let us see what you are working on. Best to share a minimum sample. 

> [!NOTE]
> Next time please use the issue templates. Thanks 🙏

**Comment by francotiveron** [comment]
See attachment
![image](https://github.com/user-attachments/assets/54575386-cf68-47e8-858a-a18d9982231c)
[Example.zip](https://github.com/user-attachments/files/18018224/Example.zip)

**Comment by timunie** [comment]
We tried your sample and have no issue to run it or preview it. Make sure it was build once at least. 

Only difference: we added both projects into one solution file, since the sln wasn't shared.

**Comment by francotiveron** [comment]
- cleaned projects (manually delete obj and bin directories), 
- Install latest Window updates
- rebooting computer
Now it works!
