### ISSUE TITLE
How to add Unity Games in Andriod or linux

### ISSUE THREAD

**Issue by jiushi97** [AvaloniaUI/Avalonia.Samples#111]
How to add Unity Games in Andriod or linux?

**Comment by timunie** [comment]
This repo is about Avalonia, not Unity. Please refer to their docs. 

https://docs.unity3d.com/6000.0/Documentation/Manual/android-sdksetup.html

**Comment by jiushi97** [comment]
I need run Unity Games in AvaloniaUI and can publish to windows、linux and Andriod。

**Comment by jiushi97** [comment]
> This repo is about Avalonia, not Unity. Please refer to their docs.
> 
> https://docs.unity3d.com/6000.0/Documentation/Manual/android-sdksetup.html

I need add Unity Games to AvaloniaUI and can publish to windows、linux and Andriod.
