### ISSUE TITLE
Add xUnit Avalonia.Headless sample for e2e testing

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia.Samples#34]
## Topics to cover

Based on https://docs.avaloniaui.net/docs/next/concepts/headless/

## Ideas for a sample

Unit test sample where:
- open a window with a viewmodel
- find a textbox
- send TextInput event
- find a button
- send a click/press event
- check that viewmodel got command with text executed

**Comment by timunie** [comment]
good sample idea as well. Unit tests get way too less attention.
