### ISSUE TITLE
when update this repository?

### ISSUE THREAD

**Issue by mzy666888** [AvaloniaUI/Avalonia.Samples#54]
## Topics to cover

the avalonia version 11 break changed , but this repo avalonia version 0.10...
when update this repository avalonia to version 11?

## Ideas for a sample

- [ ] I'll send a pull request with a proposal for a sample

**Comment by timunie** [comment]
Soon. I'm working on it in my free time. However, I also have to do some private stuff with priority, so I'll need some more days. Stay tuned.

**Comment by timunie** [comment]
@mzy666888 I'm happy to announce that the samples were updated now. If you find any wrong or misleading information while exploring them, please let me know.
