### ISSUE TITLE
ToDoListApp Compile Error Due to Wrong Parameter

### ISSUE THREAD

**Issue by tomschrot** [AvaloniaUI/Avalonia.Samples#67]
Ref: https://docs.avaloniaui.net/docs/next/tutorials/todo-list-app/process-a-new-item

The given example does not compile!

`

        Observable.Merge
        (
            addItemViewModel.OkCommand,
            addItemViewModel.CancelCommand.Select(_ => (ToDoItem?)null)
        )
        .Take(1)
        .Subscribe(newItem =>
        {
            if (newItem != null)
            {
                ToDoList.ListItems.Add(newItem );
            }
            ContentViewModel = ToDoList;
        });
`
where CS1660 error is thrown in line .Subscribe(newItem => ...

The Subscribe function awaits an IObserveable object not a lambda!

I also suggest to rather use C# patterns instead of null checking, e.g.

if (newItem != null) .... 

if (newItem is not null)...

**Comment by maxkatz6** [comment]
You are missing `using System;`.
