### ISSUE TITLE
Broken link in Pull Request template

### ISSUE THREAD

**Issue by david-c14** [AvaloniaUI/Avalonia.Samples#79]
## Describe the bug

The pull request template includes a checkbox item to consider adding a link to new samples from the AvaloniaUI documentation. The link to the documentation appears to be broken.   `https://github.com/AvaloniaUI/Documentation`

- [ ] Typos in the docs
- [ ] Missing information
- [ ] Misleading or wrong information
- [*] Outdated links
- [ ] Outdated or not working source code

## Proposed solution

Update the template.

- [ ] I'll send a pull request which should solve the issue

## Screenshots

![image](https://github.com/AvaloniaUI/Avalonia.Samples/assets/10398567/01613ac4-3cc5-40e7-8e80-0f8903e830cb)

**Comment by timunie** [comment]
good catch. Will update this on the weekend
