### ISSUE TITLE
Upgrade to .net 8

### ISSUE THREAD

**Issue by giuliohome** [AvaloniaUI/Avalonia.Samples#86]
Why are the samples still running on net6 ?

I've tried the net8 target on debian bullseye and it looks all good to me.

![image](https://github.com/AvaloniaUI/Avalonia.Samples/assets/3272563/6b7c106d-0a70-424c-96da-6eb887a86519)

**Comment by timunie** [comment]
Why do you think this is a bug? Sure Avalonia runs also with net8. However I prefer to upgrade them only if really needed. Otherwise I want to add more content instead of doing updates whenever there is  a new .NET version.

**Comment by giuliohome** [comment]
yes, it is a question not a bug.

so, I only need to edit the project and change net6 to net8 and nothing else? 

thanks
