### ISSUE TITLE
Clipboard does copy/paste objects when complied with .Net8

### ISSUE THREAD

**Issue by cornerbowlsoftware** [AvaloniaUI/Avalonia.Samples#94]
## Describe the bug
Clipboard does copy/paste objects when complied with .Net8

## Steps to Reproduce
Create a new Avalonia project.
Set the targets to: <TargetFramework>net7.0</TargetFramework>
Create a model that includes the [Serializable] attribute.  For example:

```
    [Serializable]
    public class MyTestModel
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public MyTestModel() 
        { 
        }
    }
```

Update the MainView to create the model and copy then paste the model to and from the clipboard like so:

```
public partial class MainView : UserControl
{
    public MainView()
    {
        InitializeComponent();
        Loaded += MainView_Loaded;
    }

    private void MainView_Loaded(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
    {
        TestAsync().GetAwaiter().GetResult();
    }

    private async Task TestAsync()
    {
        var m = new MyTestModel()
        {
            Id = 1,
            Name = "Test",
        };

        var dataObject = new DataObject();
        dataObject.Set("my-app-person", m);

        var clipboard = TopLevel.GetTopLevel(this)!.Clipboard!;
        await clipboard.SetDataObjectAsync(dataObject);

        var r = await clipboard.GetDataAsync("my-app-person");
        Debug.WriteLine(r);
    }
}
```
Run the program.  Notice the variable "r" is returned as expected.
Modify both Avalonia projects to target to <TargetFramework>net8.0</TargetFramework>
Run the program.  Notice the variable "r" is null.

**Comment by cornerbowlsoftware** [comment]
Oops wrong project.  Please delete me.

**Comment by cornerbowlsoftware** [comment]
Oops wrong project. Please delete me.

**Comment by timunie** [comment]
Don't do GetAwaiter.GetResult. that's evil imo
